version: '3'
services:
  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - "./nginx/config/block.conf:/etc/nginx/block.conf"
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - honeypot_network
    depends_on:
      - honeypot
      - shop
      - fail2ban

  shop:
    image: shop_image
    container_name: shop
    build:
      context: ./shop/docker
    networks:
      honeypot_network:

  honeypot:
    image: honeypot_image
    container_name: honeypot
    build:
      context: ./honeypot/docker
    ports:
      - "8081:8081"
    networks:
      honeypot_network:

  fail2ban:
    build:
      context: ./fail2ban/docker
    container_name: fail2ban
    restart: "unless-stopped"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs/suricata/fast.log:/var/log/suricata.log
      - "./logs/fail2ban:/var/log/fail2ban"
      - "./fail2ban/config:/data"
      - "/var/lib/docker/containers/:/container-logs/:ro"
      - "./nginx/config/block.conf:/etc/nginx/block.conf"
      - "./nginx/config/nginx.conf:/etc/nginx/nginx.conf"
    env_file:
      - "./fail2ban.env"
    depends_on:
      - suricata

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./logs/suricata/fast.log:/var/log/suricata/fast.log
      - ./suricata/config/suricata.yaml:/etc/suricata/suricata.yaml
      - ./suricata/config/suricata.rules:/var/lib/suricata/rules/suricata.rules
    command: -i eth0

networks:
  honeypot_network:
  dashboard_network: