name: Docker Backend

on:
  push:
    branches: [ main ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_CONFIG: ${{ github.workspace }}/.docker
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_CONFIG }}

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure Docker credentials
      run: |
        mkdir $DOCKER_CONFIG
        echo -n "$DOCKER_PASSWORD" | docker --config $DOCKER_CONFIG login --username $DOCKER_USER --password-stdin
    - name: Build the Backend image
      run: |
        docker build -t $DOCKER_USER/hb_dashboard_back .
    - name: Build the Envoy image
      run: |
        docker build -t $DOCKER_USER/hb_dashboard_envoy -f Dockerfile.envoy .
    - name: Push the images
      run: |
        docker --config $DOCKER_CONFIG push $DOCKER_USER/hb_dashboard_back
        docker --config $DOCKER_CONFIG push $DOCKER_USER/hb_dashboard_envoy
