name: Docker Frontend

on:
  push:
    branches: [ main ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_CONFIG: ${{ github.workspace }}/.docker

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure Docker credentials
      run: |
        mkdir $DOCKER_CONFIG
        echo -n "$DOCKER_PASSWORD" | docker --config $DOCKER_CONFIG login --username $DOCKER_USER --password-stdin
    - name: Clone honeypot
      run: |
        cd ..
        git clone https://github.com/Honeybrain/Honeypot
        cd Honeypot
    - name: Build protos
      run: |
        cd ../Honeypot
        chmod 777 ./scripts/make_frontend_protos.sh
        ./scripts/make_frontend_protos.sh ./protos ../Frontend
    - name: Build the Frontend image
      run: |
        docker build -t $DOCKER_USER/hb_dashboard_front .
    - name: Push the Frontend image
      run: |
        docker --config $DOCKER_CONFIG push $DOCKER_USER/hb_dashboard_front