version: "3"
services:
  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - "../../config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "../../config/nginx/block.conf:/etc/nginx/block.conf"
      - "../../logs/nginx:/var/log/nginx"
    ports:
      - "80:80"
    networks:
      - services_network
    depends_on:
      - shop

  shop:
    image: shop_image
    container_name: shop
    build:
      context: ../dockerfile/shop
    networks:
      - services_network

  dummy_pc_0:
    container_name: honeypot_dummy_pc_0
    build:
      context: ../modules/dummy_pc
      dockerfile: Dockerfile
    networks:
      honeypot_network:
        ipv4_address: 192.168.1.12

  dummy_pc_1:
    container_name: honeypot_dummy_pc_1
    build:
      context: ../modules/dummy_pc
      dockerfile: Dockerfile
    networks:
      honeypot_network:
        ipv4_address: 192.168.1.13

  dummy_pc_2:
    container_name: honeypot_dummy_pc_2
    build:
      context: ../modules/dummy_pc
      dockerfile: Dockerfile
    networks:
      honeypot_network:
        ipv4_address: 192.168.1.14

  dummy_pc_3:
    container_name: honeypot_dummy_pc_3
    build:
      context: ../modules/dummy_pc
      dockerfile: Dockerfile
    networks:
      honeypot_network:
        ipv4_address: 192.168.1.15

  ftp:
    container_name: honeypot_dummy_ftp
    build:
      context: ../modules/ftp
      dockerfile: Dockerfile
    ports:
      - "21:21"
    networks:
      honeypot_network:
        ipv4_address: 192.168.1.17

  backend:
    image: backend
    container_name: backend
    build:
      context: ../../../Backend/
      dockerfile: Dockerfile.dev
    environment:
      - GRPC_URL=backend:50051
      - SMTP_HOST=smtp.zoho.eu
      - SMTP_PORT=465
      - SMTP_FROM=contact@honeybrain.fr
      - SMTP_USER=contact@honeybrain.fr
      - SMTP_PASSWORD=H!2HQwusWch-:xc
      - CREATE_ADMIN_EMAIL=francois.bolla@epitech.eu
      - CREATE_ADMIN_PASSWORD=k6d=Ha2#~fW25OwrAffe
    networks:
      - dashboard_network
    volumes:
      - "../../config/wireguard/peer1:/app/honeypot/peer1"
      - "../../logs/suricata/fast.log:/app/honeypot/fast.log"
      - "../../config/suricata/suricata.rules:/app/honeypot/suricata.rules"
      - "../../config/fail2ban/filter.d/nginx-honeypot.conf:/app/honeypot/nginx-honeypot.conf"
      - "../../config/fail2ban/action.d/geohostsdeny.conf:/app/honeypot/geohostsdeny.conf"
      - "../../config/nginx/block.conf:/app/honeypot/block.conf"
      - ../../config/generator:/app/honeypot/generator
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "50051"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - dashboard_network

  envoy:
    container_name: envoy
    build:
      context: ../../../Backend/
      dockerfile: Dockerfile.envoy
    ports:
      - "8080:8080"
    networks:
      - dashboard_network
    depends_on:
      - backend

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ../../../Frontend/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - dashboard_network
    volumes:
      - "../../../Frontend/src:/app/src"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 3

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVERURL=92.161.57.201
      - SERVERPORT=51820
      - PEERS=1
    volumes:
      - ../../config/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - dashboard_network
    restart: unless-stopped

  generator:
    image: alpine:latest
    container_name: generator
    build:
      context: ../dockerfile/generator
      dockerfile: Dockerfile
    volumes:
      - ../../config/generator:/config

networks:
  honeypot_network:
    name: honeypot_network
    ipam:
      config:
        - subnet: 192.168.1.0/24
  services_network:
    name: services_network
  dashboard_network:
    name: dashboard_network
