version: "3"
services:
  fail2ban:
    build:
      context: ../dockerfile/fail2ban
    container_name: fail2ban
    restart: "unless-stopped"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "../../logs/suricata/fast.log:/var/log/suricata.log"
      - "../../logs/fail2ban:/var/log/fail2ban"
      - "../../config/fail2ban:/data"
      - "/var/lib/docker/containers/:/container-logs/:ro"
      - "../../config/nginx/block.conf:/etc/nginx/block.conf"
      - "../../config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    env_file:
      - "../../config/fail2ban/fail2ban.env"
    depends_on:
      - suricata

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - "../../logs/suricata/fast.log:/var/log/suricata/fast.log"
      - "../../config/suricata/suricata.yaml:/etc/suricata/suricata.yaml"
      - "../../config/suricata/suricata.rules:/var/lib/suricata/rules/suricata.rules"
    command: -i ${NETWORK_INTERFACE:-null}