name: Dummy PC Build

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the dummy PC
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        cd installers/modules/dummy_pc
        docker build -t $DOCKER_USER/hb_modules_pc .
    - name: Push the dummy PC
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push $DOCKER_USER/hb_modules_pc