name: FTP Build

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the FTP image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        cd installer/modules/ftp
        docker build -t $DOCKER_USER/hb_modules_ftp .
    - name: Push the FTP image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push $DOCKER_USER/hb_modules_ftp