name: Honeypot Modules

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_CONFIG: ${{ github.workspace }}/.docker

jobs:
  FTP_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Docker credentials
        run: |
          mkdir $DOCKER_CONFIG
          echo -n "$DOCKER_PASSWORD" | docker --config $DOCKER_CONFIG login --username $DOCKER_USER --password-stdin
      - name: Build the FTP image
        run: |
          cd docker/modules/ftp
          docker build -t $DOCKER_USER/hb_modules_ftp .
      - name: Push the FTP image
        run: |
          docker --config $DOCKER_CONFIG push $DOCKER_USER/hb_modules_ftp

  DummyPC_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Docker credentials
        run: |
          mkdir $DOCKER_CONFIG
          echo -n "$DOCKER_PASSWORD" | docker --config $DOCKER_CONFIG login --username $DOCKER_USER --password-stdin
      - name: Build the Dummy PC image
        run: |
          cd docker/modules/dummy_pc
          docker build -t $DOCKER_USER/hb_modules_pc .
      - name: Push the Dummy PC image
        run: |
          docker --config $DOCKER_CONFIG push $DOCKER_USER/hb_modules_pc
