name: Honeypot Modules

on:
  push:
    branches: [ S2-0.0/Restore_modules ]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_CONFIG: ${{ github.workspace }}/.docker

jobs:

  FTP_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the FTP image
        run: |
          cd modules/ftp
          docker build -t $DOCKER_USER/hb_modules_ftp .
      - name: Push the FTP image
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/hb_modules_ftp

  DummyPC_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Dummy pc image
        run: |
          cd modules/dummy_pc
          docker build -t $DOCKER_USER/hb_modules_pc .
      - name: Push the Dummy pc image
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/hb_modules_pc