name: Honeypot Services

on:
  push:
    branches:
      - S3-2.3/Passage_en_mono_repo

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_CONFIG: ${{ github.workspace }}/.docker

jobs:
  Fail2ban_Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Docker credentials
        run: |
          mkdir $DOCKER_CONFIG
          echo -n "$DOCKER_PASSWORD" | docker --config $DOCKER_CONFIG login --username $DOCKER_USER --password-stdin
      - name: Build the Fail2ban image
        run: |
          cd docker/dockerfile/fail2ban
          docker build -t $DOCKER_USER/hb_services_fail2ban .
      # - name: Push the Fail2ban image
      #   run: |
      #     docker --config $DOCKER_CONFIG push $DOCKER_USER/hb_services_fail2ban
