name: Trigger VPS update

on:
  push:
    branches:
      - Fix_vps

env:
  HOST: ${{ secrets.VPS_HOST }}
  USER: ${{ secrets.VPS_USER }}
  PASSWD: ${{ secrets.VPS_PASSWD }}
  PORT: ${{ secrets.VPS_PORT }}

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute script on VPS
        uses: appleboy/ssh-action@master
        with:
          host: $HOST
          username: $USER
          password: $PASSWD
          port: $PORT
          script: |
            cd /home/honeybrain/Honeybrain/Honeypot
            ./scripts/auto_update_vps.sh > /home/honeybrain/Honeybrain/update.log