name: Trigger VPS update

on:
  push:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute script on VPS
        uses: appleboy/ssh-action@master
        env:
          PROJECT_PATH: /home/honeybrain/Honeybrain
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd $PROJECT_PATH/Honeypot
            ./auto_update_vps.sh > $PROJECT_PATH/update.log
