name: Trigger VPS update

on:
  push:
    branches:
      - Fix_vps

env:
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_USER: ${{ secrets.VPS_USER }}
  VPS_PASSWD: ${{ secrets.VPS_PASSWD }}
  VPS_PORT: ${{ secrets.VPS_PORT }}

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute script on VPS
        uses: appleboy/ssh-action@master
        with:
          host: $VPS_HOST
          username: $VPS_USER
          password: $VPS_PASSWD
          port: $VPS_PORT
          script: |
            cd /home/honeybrain/Honeybrain/Honeypot
            ./scripts/auto_update_vps.sh > /home/honeybrain/Honeybrain/update.log
